SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CastMembers](
	[ShowId] [int] NOT NULL,
	[MemberId] [int] NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Birthdate] [date] NULL,
 CONSTRAINT [PK_CastMembers] PRIMARY KEY CLUSTERED 
(
	[ShowId] ASC,
	[MemberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CastMembers]  WITH CHECK ADD  CONSTRAINT [FK_CastMembers_Shows] FOREIGN KEY([ShowId])
REFERENCES [dbo].[Shows] ([Id])
GO

ALTER TABLE [dbo].[CastMembers] CHECK CONSTRAINT [FK_CastMembers_Shows]
GO


