// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvMazeScraper.Infrastructure.Sql.Model;

namespace TvMazeScraper.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(ShowContext))]
    [Migration("20181129143551_LastModified")]
    partial class LastModified
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TvMazeScraper.Infrastructure.Sql.Model.CastMember", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CastMembers");
                });

            modelBuilder.Entity("TvMazeScraper.Infrastructure.Sql.Model.Show", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("ImdbId");

                    b.Property<decimal?>("ImdbRating");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("TvMazeScraper.Infrastructure.Sql.Model.ShowCastMember", b =>
                {
                    b.Property<int>("ShowId");

                    b.Property<int>("CastMemberId");

                    b.HasKey("ShowId", "CastMemberId");

                    b.HasIndex("CastMemberId");

                    b.ToTable("ShowCastMembers");
                });

            modelBuilder.Entity("TvMazeScraper.Infrastructure.Sql.Model.ShowCastMember", b =>
                {
                    b.HasOne("TvMazeScraper.Infrastructure.Sql.Model.CastMember", "CastMember")
                        .WithMany("ShowCastMembers")
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TvMazeScraper.Infrastructure.Sql.Model.Show", "Show")
                        .WithMany("ShowCastMembers")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
