// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RtlTvMazeScraper.Infrastructure.Sql.Model;

namespace RtlTvMazeScraper.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(ShowContext))]
    partial class ShowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RtlTvMazeScraper.Core.Model.CastMember", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CastMembers");
                });

            modelBuilder.Entity("RtlTvMazeScraper.Core.Model.Show", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("RtlTvMazeScraper.Core.Model.ShowCastMember", b =>
                {
                    b.Property<int>("ShowId");

                    b.Property<int>("CastMemberId");

                    b.HasKey("ShowId", "CastMemberId");

                    b.HasIndex("CastMemberId");

                    b.ToTable("ShowCastMembers");
                });

            modelBuilder.Entity("RtlTvMazeScraper.Core.Model.ShowCastMember", b =>
                {
                    b.HasOne("RtlTvMazeScraper.Core.Model.CastMember", "CastMember")
                        .WithMany("ShowCastMembers")
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RtlTvMazeScraper.Core.Model.Show", "Show")
                        .WithMany("ShowCastMembers")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
